### ISSUE TITLE
Change package name to genometools-scripts

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools-scripts#3]
I think the package name would be more descriptive if it included the unabbreviated name `genometools`. I suggest changing the name to `genometools-scripts`.

This may be a bike shed argument. I won't take offence if you disagree.

**Comment by satta** [comment]
That would be fine with me. What do the others think? If yes, we should do this as early as possible as long as the number of forkers etc. is still low...

**Comment by standage** [comment]
:+1:

**Comment by gordon** [comment]
Fine with me.

**Comment by satta** [comment]
Done!

**Comment by sjackman** [comment]
Thanks!
